config/urls.py
from django.contrib import admin
from django.urls import path, include
from reimburse.views import (index, view, add, delete,download, edit, redraft,
         submit, paid, reject, waiting, involved)

urlpatterns = [
    path("",index, name="reimburse-index"),
    path("waiting/",waiting, name="reimburse-waiting"),
    path("involved/",involved, name="reimburse-involved"),
    path("add/",add, name="reimburse-add"),
    path("download/<int:id>", download, name="reimburse-download"),
    path("view/<int:id>", view, name="reimburse-view"),
    path("redraft/<int:id>", redraft, name="reimburse-redraft"),
    path("edit/<int:id>", edit, name="reimburse-edit"),
    path("delete/<int:id>", delete, name="reimburse-delete"),
    path("submit/<int:id>", submit, name="reimburse-submit"),
    path("paid/<int:id>", paid, name="reimburse-paid"),
    path("reject/<int:id>", reject, name="reimburse-reject"),
    path('oidc/', include('mozilla_django_oidc.urls')),
    path('admin/', admin.site.urls),
]

apps/reimburse/models.py
from decimal import Decimal
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User


class Reimburse(models.Model):
    DRAFT = "D"
    SUBMIT = "S"
    PAID = "P"
    REJECT = "R"

    STATE = [
        (DRAFT, "Draft"),
        (SUBMIT, "Waiting Approval"),
        (PAID, "Paid"),
        (REJECT, "Rejected"),
    ]


    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reimburse_user_set")
    approver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reimburse_approver_set")
    title = models.CharField(max_length=255)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    total = models.IntegerField(default=0)
    state = models.CharField(max_length=1, choices=STATE, default=DRAFT)

    def __str__(self):
        return self.title

class ReimburseHistory(models.Model):
    reimburse = models.ForeignKey(Reimburse, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=255)

class ReimburseLine(models.Model):
    reimburse = models.ForeignKey(Reimburse, on_delete=models.CASCADE)
    item = models.CharField(max_length=255)
    attachment = models.FileField(upload_to="reimburse_attachment")
    quantity = models.IntegerField(default=1)
    price = models.IntegerField(default=0)
    subtotal = models.IntegerField(default=0)

apps/reimburse/forms.py
from django import forms
from crispy_formset_modal.helper import ModalEditFormHelper
from crispy_formset_modal.layout import ModalEditFormsetLayout
from crispy_formset_modal.layout import ModalEditLayout
from crispy_forms.layout import Column, Fieldset, Layout, Row, Submit, Field
from crispy_forms.helper import FormHelper
from .models import Reimburse, ReimburseLine



class DateInput(forms.DateInput):
    input_type = "date"

    def __init__(self, attrs=None):
        super().__init__(attrs)

class ReimburseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column(
                    Field("title"),
                    Field("description")
                ), 
                Column(
                    Field("approver"),
                    Row(Column(Field("start_date")), Column(Field("end_date"))),
                )
            ),
        )
        super(ReimburseForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Reimburse
        exclude = ['created_date', 'total', 'state']
        widgets = {
                'user': forms.HiddenInput(),
                "start_date": DateInput(),
                "end_date": DateInput()}

class LineForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = 'form-inline'
        self.helper.field_template = 'bootstrap5/layout/inline_field.html'
        self.helper.layout = Layout(
            Row(
            Column(Field('item')),
            Column(Field('attachment')),
            Column(Field('quantity')),
            Column(Field('price')),
            )
        )
        super(LineForm, self).__init__(*args, **kwargs)
    
    class Meta:
        model = ReimburseLine
        fields = "__all__"

apps/reimburse/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import login_required
from .models import Reimburse, ReimburseLine
from .forms import ReimburseForm, LineForm

@login_required
def index(request):
    docs = Reimburse.objects.filter(user=request.user)
    return render(request, "index.html", locals())

@login_required
def waiting(request):
    docs = Reimburse.objects.filter(approver=request.user, state=Reimburse.SUBMIT)
    return render(request, "index.html", locals())

@login_required
def involved(request):
    docs = Reimburse.objects.filter(approver=request.user).exclude(
            state__in=[Reimburse.DRAFT, Reimburse.SUBMIT])
    return render(request, "index.html", locals())

@login_required
def view(request, id):
    doc = Reimburse.objects.get(id=id)
    return render(request, "view.html", locals())

@login_required
def delete(request, id):
    doc = Reimburse.objects.get(id=id)
    doc.delete()
    return redirect("reimburse-index")

@login_required
def download(request, id):
    doc = ReimburseLine.objects.get(id=id)
    cont = doc.attachment.read()
    response = HttpResponse(cont)
    response['Content-Disposition'] = 'attachment; filename=%s' % doc.attachment.name
    return response


@login_required
def submit(request, id):
    doc = Reimburse.objects.get(id=id)
    if request.user != doc.user or doc.state != Reimburse.DRAFT:
        return redirect("reimburse-index")
    doc.state = Reimburse.SUBMIT
    doc.save()
    return redirect("reimburse-view", id=id)

@login_required
def paid(request, id):
    doc = Reimburse.objects.get(id=id)
    if request.user != doc.approver or doc.state != Reimburse.SUBMIT:
        return redirect("reimburse-index")
    doc.state = Reimburse.PAID
    doc.save()
    return redirect("reimburse-view", id=id)

@login_required
def reject(request, id):
    doc = Reimburse.objects.get(id=id)
    if request.user != doc.approver or doc.state != Reimburse.SUBMIT:
        return redirect("reimburse-index")
    doc.state = Reimburse.REJECT
    doc.save()
    return redirect("reimburse-view", id=id)

@login_required
def redraft(request, id):
    doc = Reimburse.objects.get(id=id)
    if request.user != doc.user or doc.state != Reimburse.REJECT:
        return redirect("reimburse-index")
    doc.state = "RD"
    doc.save()
    return redirect("reimburse-view", id=id)

@login_required
def edit(request, id):
    instance = Reimburse.objects.get(id=id)
    form = ReimburseForm(instance=instance)
    LineFormSet = inlineformset_factory(Reimburse, ReimburseLine, extra=2, form=LineForm, fields=["item",'attachment', "quantity", "price"])
    formset = LineFormSet( instance=instance, prefix="nested")
    if request.method == "POST":
        data = request.POST.copy()
        data['user'] = request.user
        form = ReimburseForm(data,  request.FILES, instance=instance)
        if form.is_valid():
            jd = form.save()
            print(request.FILES)
            formset = LineFormSet(request.POST,  request.FILES, instance=instance, prefix="nested")
            if  formset.is_valid():
                formset.save()
                return redirect("reimburse-view", id=jd.id)
            else:
                print(formset.errors)
    return render(request, "edit.html", locals())

@login_required
def add(request):
    form = ReimburseForm()
    LineFormSet = inlineformset_factory(Reimburse, ReimburseLine, form=LineForm, fields=["item",'attachment', "quantity", "price"])
    formset = LineFormSet( prefix="nested")
    if request.method == "POST":
        data = request.POST.copy()
        data['user'] = request.user
        form = ReimburseForm(data, request.FILES)
        if form.is_valid():
            jd = form.save()
            formset = LineFormSet(data, request.FILES, instance=jd, prefix="nested")
            if  formset.is_valid():
                formset.save()
                return redirect("reimburse-view", id=jd.id)
    return render(request, "add.html", locals())

apps/reimburse/templates/add.html
{% extends 'bootstrap5/bootstrap5.html' %}
{% load bootstrap5 %}
{% load static %}
{% load crispy_forms_tags %}

{% block bootstrap5_title %}Create Reimburse{% endblock %}

{% block bootstrap5_extra_head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'crispy_formset_modal/js/crispy-formset-modal.min.js' %}"></script>
{% endblock%}

{% block bootstrap5_content %}
    <div class="container mx-auto mt-4">
      <h1>{% block title %} Create Reimburse {% endblock %}</h1>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}
         <form role="form" enctype="multipart/form-data" action=""  method="post">
            {% csrf_token %}
            {% crispy form %}
            {% crispy formset formset.form.helper %}
             <input class="btn btn-success" type="submit" value="Submit data">
        </form>
        {% endblock %}
    </div>
{% endblock %}

apps/reimburse/templates/edit.html
{% extends 'bootstrap5/bootstrap5.html' %}
{% load bootstrap5 %}
{% load static %}
{% load crispy_forms_tags %}

{% block bootstrap5_title %}Create Reimburse{% endblock %}

{% block bootstrap5_extra_head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'crispy_formset_modal/js/crispy-formset-modal.min.js' %}"></script>
{% endblock%}

{% block bootstrap5_content %}
    <div class="container mx-auto mt-4">
      <h1>{% block title %} Create Reimburse {% endblock %}</h1>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}
         <form enctype="multipart/form-data" role="form" action=""  method="post">
            {% csrf_token %}
            {% crispy form %}
            {% crispy formset formset.form.helper %}
             <input class="btn btn-success" type="submit" value="Save">
             <a href="{% url 'reimburse-view' instance.id %}" class="btn btn-danger">Cancel</a>
        </form>
        {% endblock %}
    </div>
{% endblock %}

apps/reimburse/templates/index.html
{% extends 'bootstrap5/bootstrap5.html' %}
{% load bootstrap5 %}
{% load static %}

{% block bootstrap5_extra_head %}
<script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
<link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block bootstrap5_title %}Portal{% endblock %}

{% block bootstrap5_content %}
    <div class="container mx-auto mt-4">
      <h1>{% block title %} Selamat datang, {{ request.user.username }}{% endblock %}</h1>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}
        <table class="table table-striped">
            <tr>
                <th>Title</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Total</th>
                <th>State</th>
                <th>Action</th>
            </tr>
            {% for itm in docs %}
            <tr>
                <td>{{ itm.title }}</td>
                <td>{{ itm.start_date }}</td>
                <td>{{ itm.end_date }}</td>
                <td>Rp. {{ itm.total }},-</td>
                <td>{{ itm.get_state_display }}</td>
                <td>
                    <a href="{% url 'reimburse-view' itm.id %}" class="btn btn-success">View</a>
                    {% if itm.state == "D"%}
                    <a href="{% url 'reimburse-edit' itm.id  %}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'reimburse-delete' itm.id %}" onclick="if (confirm('Delete selected item?')){return true;}else{event.stopPropagation(); event.preventDefault();};"  class="btn btn-danger">Delete</a>
                    {% endif  %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <a href="{% url 'reimburse-add' %}" class="btn btn-success">Add</a>
        <a href="{% url 'reimburse-index' %}" class="btn btn-secondary">My Document</a>
        <a href="{% url 'reimburse-waiting' %}" class="btn btn-primary">Waiting Approval Document</a>
        <a href="{% url 'reimburse-involved' %}" class="btn btn-warning">Involved Document</a>
        {% endblock %}
    </div>

{% endblock %}

apps/reimburse/templates/view.html
{% extends 'bootstrap5/bootstrap5.html' %}
{% load bootstrap5 %}
{% load static %}

{% block bootstrap5_extra_head %}
<script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
<link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block bootstrap5_title %}Portal{% endblock %}

{% block bootstrap5_content %}
    <div class="container mb-4 mt-4">
      <h1>{% block title %} Reimburse Detail {% endblock %}</h1>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}
        <div class="row">
           <div class="col-xl-6">
        <table class="table table-borderless">
            <tr>
                <th>Title</th><td>:</td><td>{{ doc.title }}</td>
            </tr>
            <tr>
                <th>Start Date</th><td>:</td><td>{{ doc.start_date }}</td>
            </tr>
            <tr>
                <th>End Date</th><td>:</td><td>{{ doc.end_date }}</td>
            </tr>
            <tr>
                <th>Description</th><td>:</td><td>{{ doc.description }}</td>
            </tr>
            <tr>
                <th>Approver</th><td>:</td><td>{{ doc.approver }}</td>
            </tr>
            <tr>
                <th>State</th><td>:</td><td>{{ doc.get_state_display }}</td>
            </tr>
        </table>
        </div>
        <div class="col-xl-6">
<h2>History</h2>
        <table class="table table-striped">
            <tr>
                <th>User</th>
                <th>Date</th>
                <th>Message</th>
            </tr>
            {% for itm in doc.reimbursehistory_set.all %}
            <tr>
                <td>{{ itm.user }}</td>
                <td>{{ itm.created_date }}</td>
                <td>{{ itm.message }}</td>
            </tr>
            {% endfor %}
        </table>
        </div>
        </div>

      

        <h2>Item Detail</h2>
        <table class="table table-striped">
            <tr>
                <th>Item</th>
                <th>Attachment</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Sub Total</th>
            </tr>
            {% for itm in doc.reimburseline_set.all %}
            <tr>
                <td>{{ itm.item }}</td>
                <td><a href="{% url 'reimburse-download' itm.id %}">Download</a></td>
                <td>{{ itm.quantity }}</td>
                <td>Rp. {{ itm.price }},-</td>
                <td>Rp. {{ itm.subtotal }},-</td>
            </tr>
            {% empty %}
            <tr class="table-danger" ><td colspan="5" style="text-align:center;">No Data</td><tr>
            {% endfor %}
            <tr class="table-primary">
                <td colspan="4">Total</td>
                <td>Rp {{doc.total}},-</td>
           </tr> 
        </table>
        <a href="{% url 'reimburse-index' %}" class="btn btn-primary">Back</a>
                    {% if doc.state == "R" and doc.user == request.user %}
                    <a href="{% url 'reimburse-redraft' doc.id %}" class="btn btn-success">Redraft</a>
                    {% endif %}
        {% if doc.state == "D" and doc.user == request.user %}
        {% if doc.total > 0 %}
        <a href="{% url 'reimburse-submit' doc.id %}" class="btn btn-success">Submit</a>
        {% endif %}
        <a href="{% url 'reimburse-edit' doc.id %}" class="btn btn-warning">Edit</a>
        <a href="{% url 'reimburse-delete' doc.id %}" onclick="if (confirm('Delete selected item?')){return true;}else{event.stopPropagation(); event.preventDefault();};"  class="btn btn-danger">Delete</a>
        {% endif %}
        {% if doc.state == "S" and doc.approver == request.user %}
        <a href="{% url 'reimburse-paid' doc.id %}" class="btn btn-warning">Paid</a>
        <a href="{% url 'reimburse-reject' doc.id %}" class="btn btn-danger">Reject</a>
        {% endif %}
        </br>
       {% endblock %}
    </div>

{% endblock %}